title: Wilfred Chan
description: Wilfred Chan's Data Repository
author: Wilfred Chan
logo: static/img/avatar.png
github: https://wilfredchankwong.github.io
about: Python, R, SQ, Machine Learning

baseurl: "https://wilfredchankwong.github.io"
url: "https://wilfredchankwong.github.io"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
